language: r
sudo: false
cache: packages

repos:
  CRAN: https://cloud.r-project.org
  IRkernel: https://irkernel.github.io/

addons:
  apt:
    packages:
      # Install the headers for the Cairo package.
      - libcairo2-dev
      - libjpeg-dev

#script:
#  - "grep -q 'Status: 1 NOTE' ~/build/IRkernel/repr/repr.Rcheck/00check.log"
